DROP TABLE ExchangeRate
DROP TABLE Bill
DROP TABLE Users
DROP TABLE Currency
DROP TABLE Category

CREATE TABLE Users (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT(NEWID()),
	CreatedOn DATETIME2 NOT NULL DEFAULT(GETUTCDATE()),
	Email NVARCHAR(250) NOT NULL,
	Password NVARCHAR(250) NOT NULL,
	Username NVARCHAR(250) NOT NULL
)

CREATE TABLE Currency (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT(NEWID()),
	Name NVARCHAR(10) NOT NULL,
	CONSTRAINT UC_Name UNIQUE (Name)
)


CREATE TABLE ExchangeRate (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT(NEWID()),
	[Date] DATE NOT NULL DEFAULT(GETDATE()),
	[From] UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_ExchangeRateFromCurrency REFERENCES Currency(Id),
	[To] UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_ExchangeRateToCurrency REFERENCES Currency(Id),
	[Rate] DECIMAL(18, 6) CHECK([Rate] > 0),
	CONSTRAINT UC_FromTo UNIQUE([From], [To])
)


CREATE TABLE Bill (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT(NEWID()),
	UserId UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_BillUser REFERENCES Users(Id),
	Currency UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_BillCurrency REFERENCES Currency(Id),
	[Amount] DECIMAL(18, 2) CHECK([Amount] > 0)
)

CREATE TABLE Category (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT(NEWID()),
	Name NVARCHAR(100) NOT NULL,
	Capacity INT NOT NULL CHECK(Capacity > 0)
	CONSTRAINT UC_Category_Name UNIQUE (Name)
)
